
server:
  port: 8081

spring:
  datasource:
    dynamic:
      enable: true
      collection:
        default:
          url: jdbc:mysql://10.10.116.15:3306/bird-demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
          username: root
          password: Thctlrb888
          driver-class-name: com.mysql.jdbc.Driver
        db2:
          url: jdbc:mysql://10.10.116.15:3306/bird-demo2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
          username: root
          password: Thctlrb888
          driver-class-name: com.mysql.jdbc.Driver


  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: xxx
    timeout: 30000

mybatis-plus:
  mapper-locations: classpath*:com/bird/service/sample/**/*.xml
  type-aliases-package: com.bird.service.sample.**.model*
  configuration:
    call-setters-on-nulls: true
  global-config:
    id-type: 1
    db-column-underline: false
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    meta-object-handler: com.bird.service.common.mapper.injector.AuditMetaObjectHandler
